apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  labels:
    app: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: gitea
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      containers:
        - name: gitea
          image: gitea/gitea:1.23
          ports:
            - containerPort: 3000
              name: http
            - containerPort: 2242
              name: ssh
          env:
            - name: USER_UID
              value: "1000"
            - name: USER_GID
              value: "1000"
            - name: DEFAULT_BRANCH
              value: "master"
            - name: ROOT_URL
              value: "https://scm.bstein.dev"
            - name: DB_TYPE
              value: "postgres"
            - name: DB_HOST
              value: "postgres-service.postgres.svc.cluster.local:5432"
            - name: DB_NAME
              value: "gitea"
            - name: DB_USER
              value: "gitea"
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: gitea-db-secret
                  key: password
            - name: START_SSH_SERVER
              value: "true"
            - name: SSH_PORT
              value: "2242"
          volumeMounts:
            - name: gitea-data
              mountPath: /data
      volumes:
        - name: gitea-data
          persistentVolumeClaim:
            claimName: gitea-data
