apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gitea
  namespace: flux-system
spec:
  interval: 10m
  path: "./apps/production/gitea"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
