# flux_bootstrap/apps/gitea/kustomization.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gitea
  namespace: flux-system
spec:
  interval: 10m
  path: "./apps/gitea"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux_bootstrap
  validation: client

